name: Erlang CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ['22.3', '23.3', '24.0']
        rebar: ['3.16.1']
        include:
        - otp: '21.3'
          rebar: '3.15.2'

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar}}
    - name: Compile
      run: rebar3 compile
    - name: Format check
      run: rebar3 format --verify
    - name: Run tests and verifications
      run: rebar3 dialyzer || rebar3 test # first dialyzer run always complains and 'test' alias runs dialyzer
