name: Erlang CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [21.3, 22.3, 23.0.4, 23.2.7.0, 24.0]
    container:
      image: erlang:${{ matrix.otp }}-alpine

    steps:
    - uses: actions/checkout@v2
    - name: Get latest rebar3
      run: rebar3 --version && rebar3 local upgrade && rebar3 --version
    - name: Compile
      run: rebar3 compile
    - name: Format check
      run: rebar3 format --verify
    - name: Run tests and verifications
      run: rebar3 dialyzer || rebar3 test
