name: Erlang CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [21.3, 22.0.7, 22.3, 23.0.4, 23.2.7.0]
    container:
      image: erlang:${{ matrix.otp }}-alpine

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Format check
      run: rebar3 format --verify
    - name: Run tests and verifications
      run: rebar3 dialyzer || rebar3 test
